# Generated by Django 2.2.16 on 2021-10-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210929_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Поле заголовка поста', max_length=200, null=True, verbose_name='Заголовок поста'),
        ),
    ]
