# Generated by Django 2.2.16 on 2021-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211018_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Поле заголовка поста', max_length=200, null=True, verbose_name='Заголовок поста'),
        ),
    ]
