# Generated by Django 2.2.16 on 2021-10-19 06:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211019_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Поле для ввода комментария', verbose_name='Комментарий'),
        ),
    ]
