# Generated by Django 2.2.16 on 2021-09-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Поле для ввода имени скрипта', max_length=200, verbose_name='Имя скрипта')),
                ('slug', models.SlugField(help_text='Поле для ввода slug', max_length=200, unique=True, verbose_name='slug')),
                ('text', models.TextField(help_text='Поле для ввода техта скрипта', verbose_name='техт скрипта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата публикации', verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='автор публикации', on_delete=django.db.models.deletion.CASCADE, related_name='myscripts', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Поле для ввода комментария', verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата комментария', verbose_name='Дата комментария')),
                ('author', models.ForeignKey(help_text='выберите автора', on_delete=django.db.models.deletion.CASCADE, related_name='comments_blog', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('myscripts', models.ForeignKey(blank=True, help_text='Выберите пост', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_blog', to='blog.MyScripts', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
    ]
